### ISSUE TITLE
Improve the README.md

### ISSUE THREAD

**Issue by vaibhav111tandon** [vaibhav111tandon/vov.css#8]
Add the usage of classes through JavaScript and jQuery

**Comment by akhilkh2000** [comment]
Can you explain this issue in detail?

**Comment by vaibhav111tandon** [comment]
You can give a short jquery or javascript snippet to use these animation classes. A short demo type...

**Comment by gurman8571** [comment]
still open???

**Comment by chimok** [comment]
Hello @vaibhav111tandon,

i could add my snippet from #34 which is a frequently use for such animations

**Comment by chimok** [comment]
@vaibhav111tandon This is my javascript how i add css classes when the element is in viewport

```javascript
/**
 * Add a css class when the element appears in viewport
 *
 * @param {IntersectionObserverEntry[]} entries
 */
function func2(entries) {
    entries.forEach(entry => {
        const elem = entry.target;
        if (entry.isIntersecting) {
            elem.classList.add('in-viewport');
            observer.unobserve(elem);
        }
    })
}

const observer = new IntersectionObserver(func2, {
    root: null,
    rootMargin: '0px',
    threshold: .5
});

/**
 * Set or remove a css class when the element is in viewport
 *
 * @param {string} selector
 */
export function inViewport(selector = '.if-viewport') {
    document.querySelectorAll(selector).forEach(elem => {
        observer.observe(elem);
    });
}
```
The HTML looks like:
```html
<div class="if-viewport vov fade-in-up">
  This is some content with a fade-in-up animation when if appears in viewport
</div>
```

The javascript adds the `in-viewport` css class if element is in viewport.

The issue I have, the initial state before it is visible in the viewport should be `opacity:0` and placed with a bottom offset. Are there CSS classes for it already?

**Comment by vaibhav111tandon** [comment]
@chimok for the above you can set the initial styles to the in-viewport and if-viewport
```css
/* Initial hidden state */
.if-viewport {
    opacity: 0;
    transform: translateX(100px); /* Adjust for the desired initial position */
    transition: opacity 0.5s ease, transform 0.5s ease; /* Smooth transition */
}

/* Active state when in the viewport */
.in-viewport {
    opacity: 1;
    transform: translateX(0); /* Bring element to its final position */
}

```
